# Generated by Django 4.2.6 on 2023-10-10 04:44

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(default='none', upload_to=jobs.models.candidate_cv_upload),
        ),
    ]
